"""empty message

Revision ID: 139ab05ded21
Revises: 67f4fa96462f
Create Date: 2024-12-10 18:49:29.983324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139ab05ded21'
down_revision = '67f4fa96462f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_items', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_number', sa.String(length=36), nullable=False))
        
        # Provide a custom name for the unique constraint
        batch_op.create_unique_constraint('uq_order_number', ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # Provide the same constraint name when dropping the constraint
        batch_op.drop_constraint('uq_order_number', type_='unique')
        batch_op.drop_column('order_number')
        batch_op.drop_column('total_items')

    # ### end Alembic commands ###
