"""Try Drop

Revision ID: a24af13c5e1c
Revises: 41ece915034e
Create Date: 2024-12-30 03:11:10.943427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24af13c5e1c'
down_revision = '41ece915034e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('price_at_addition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_at_addition', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
