"""Add Cart and CartItem tables

Revision ID: e14fd1c7ac7b
Revises: 139ab05ded21
Create Date: 2024-12-21 14:59:18.135197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14fd1c7ac7b'
down_revision = '139ab05ded21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_addition', sa.Float(), nullable=False),  # Old column to be replaced
    sa.Column('price', sa.Float(), nullable=True),  # New column
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Migrate the data from `price_at_addition` to `price`
    op.execute('UPDATE cart_items SET price = price_at_addition')

    # Drop the `price_at_addition` column after the data migration
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('price_at_addition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
